### ISSUE TITLE
仓库好像克隆不下来

### ISSUE THREAD

**Issue by Alexhaoge** [ljk5403/libnku#2]
不管是`github desktop`还是`zip本地导入`还是`git clone https://github.com/ljk5403/libnku.git `都会有如下错误

> error: invalid path 'D绫昏/鑽敤妞嶇墿瀛?2016绾?鑽敤妞嶇墿瀛?2016绾э紙6寮?椤碉紝鎵撳嵃鐢級.zip'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

应该是这个文件命名的问题，git可能遇到`:`会报错，建议重命名
> https://github.com/ljk5403/libnku/raw/master/D类课/药用植物学-2016级/药用植物学-2016级（6张:页，打印用）.zip

**Comment by Alexhaoge** [comment]
github网页上传不了大于25MB的文件，我没法直接处理，现在也clone不下来，只能靠坤哥你一个人的本地仓库了

**Comment by ljk5403** [comment]
懂了，应该是文件名中的":"号的问题，在macOS中使用系统自动替换文件名中的“/”为“:“，我注意一下不要再使用英文斜杠
